### ISSUE TITLE
Do not request the user, can open the bluetooth on phone?

### ISSUE THREAD

**Issue by shizhidi** [randdusing/cordova-plugin-bluetoothle#362]
use bluetoothle.initialize or bluetoothle.enable?????

**Comment by phy25** [comment]
`bluetoothle.initialize` is to initialize the port. Due to Android's design, you are not able to turn on bluetooth without prompting in a normal system. By `bluetoothle.enable` Android will prompt user to accpet the request and turn on bluetooth.

By the way why don't you read `readme.md` carefully? That's concrete enough.

**Comment by shizhidi** [comment]
@phy25 谢谢，因为只是有这个需求，考虑到蓝牙耗电。想APP启动蓝牙传输数据过来，传完关闭蓝牙。看来不是太好做。感觉跟浏览器获取用户地址是一个意思。

**Comment by randdusing** [comment]
Please re-open
