### ISSUE TITLE
Build Error with latest Version

### ISSUE THREAD

**Issue by EinfachHans** [randdusing/cordova-plugin-bluetoothle#706]
With the merged PR #696 i can not build my App anymore:

**variable returnObj is already defined in method onNotificationSent(android.bluetooth.BluetoothDevice,int)**

We have `JSONObject returnObj = new JSONObject();` in line 4748 and in line 4728

**Comment by randdusing** [comment]
@VinardoZzZ2000 Can you fix this asap? If not, I may need to revert the PR. I don't have any Android devices, so I'm not confident in making the changes myself

**Comment by phatpaul** [comment]
I'm also getting the build error.  I reverted this plugin to 6.5.1 for now.

**Comment by EinfachHans** [comment]
Also i don't like the fact that it could cause a callback to be fired twice^^

**Comment by tigohenryschultz** [comment]
![image](https://user-images.githubusercontent.com/75696293/127403797-7ad96f0a-7557-41ed-91eb-116accc6fe57.png)

**Comment by randdusing** [comment]
I reverted this

**Comment by VinardoZzZ2000** [comment]
Very sorry about this. My project uses a build without the old callback, so I thought there wouldn't be any problems just adding back the old callback, and skipped the build process. I'll prepare another PR soon. Would it be preferrable to also remove the old callback immediately instead of deprecating it?

**Comment by EinfachHans** [comment]
As this is reverted, i will close this issue
